# Generated by Django 6.1 on 2026-08-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_convertido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_conversao', models.DateTimeField(auto_now_add=True)),
                ('moeda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_destino', to='conversor.moeda')),
                ('moeda_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_origem', to='conversor.moeda')),
            ],
        ),
    ]
